# frozen_string_literal: true

require 'pry'

# SATS4LIKES
TOKEN_KEY = ENV['TOKEN_KEY']
REFRESH_TOKEN = ENV['REFRESH_TOKEN']
FIREBASE_WENSOCKET_SUBDOMAIN = ENV['FIREBASE_WENSOCKET_SUBDOMAIN']

# TWITTER
TWITTER_CONSUMER_KEY    = ENV['TWITTER_CONSUMER_KEY']
TWITTER_CONSUMER_SECRET = ENV['TWITTER_CONSUMER_SECRET']
TWITTER_ACCESS_TOKEN    = ENV['TWITTER_ACCESS_TOKEN']
TWITTER_ACCESS_SECRET   = ENV['TWITTER_ACCESS_SECRET']